In [1]:
import numpy as np

In [2]:
a = np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a = np.arange(10) **2

In [5]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
a[2:9:2]

array([ 4, 16, 36, 64])